---
- name: Install the version '1.18.0' of package "nginx" and allow potential downgrades
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Restart service nginx, in all cases
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes    

- name: check nginx port
  uri:
    url: http://localhost:80
    method: GET
    status_code: 200