---
- name: Install PHP and required extensions
  block:
    - name: Install the ppa:ondrej/php repo # menambahkan repository ondrej untuk install php dengan versi spesifik
      apt_repository:
        repo: ppa:ondrej/php
        update_cache: yes
      when: "'Ubuntu' in ansible_distribution"   
      # install php dengan versi yang ditentukan
    - name: Install PHP with a certain version 
      ansible.builtin.apt:
        name: "php{{ php_version }}"
        state: present
        install_recommends: no
      # install extensi PHP yang dibutuhkan saat deployment aplikasi
    - name: Install PHP packages 
      apt:
        name:
          - php{{ php_version }}-common
          - php{{ php_version }}-curl
          - php{{ php_version }}-intl
          - php{{ php_version }}-zip
          - php{{ php_version }}-fpm
          - php{{ php_version }}-gd
          - php{{ php_version }}-mbstring
          - php{{ php_version }}-mcrypt
          - php{{ php_version }}-mysqlnd
          - php{{ php_version }}-odbc
          - php{{ php_version }}-mysql
          - php{{ php_version }}-soap
          - php{{ php_version }}-xml
          - php{{ php_version }}-xmlrpc
          - php{{ php_version }}-soap
          - php{{ php_version }}-redis
          - php{{ php_version }}-dev
          - php{{ php_version }}-imap
          - php{{ php_version }}-imagick
          - php{{ php_version }}-bcmath
          - php{{ php_version }}-json
          - php{{ php_version }}-exif
        update_cache: yes
        state: present